databases:
  - name: booksiru
    databaseName: booksiru_db
    user: taiji
    region: singapore

services:
  - type: web
    name: booksiru
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booksiru_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

